remote_theme: HamilM/plainwhite-jekyll 
title: Matan Hamilis
email: matan.hamilis@gmail.com
plainwhite:
    name: Matan Hamilis
    tagline: Log things I find interesting
    date_format: "%b %-d, %Y"
    social_links:
        github: HamilM
    sitemap: true
    show_excerpts: true
    navigation:
        - title: My Work
          url: "/my-work"
        - title: Resume
          url: "/resume"
